Better docs
AFM-SPM/TopoStats pull request #133
Opened 2022-05-11 16:42 UTC by bobturneruk

Reorganises docs moving content into readthedocs where appropriate leading to a more readable readme.

2022-05-12 11:50 UTC, ns-rse commented on docs/introduction.md
> +Image progessing is performed using the 'pygwytracing' script
Typo...

```suggestion
Image processing is performed using the 'pygwytracing' script
```

2022-05-12 12:18 UTC, ns-rse requested changes
Thanks for splitting this all up @bobturneruk .

Very minor suggestions, and we'll have to go through the process of documenting with clear examples once we have changes merged to `dev`.

2022-05-12 12:18 UTC, ns-rse commented on README.md
>  | [How it works](#how-it-works) | [Run using Docker](#run-using-docker) | [Parameter Configuration](#parameter-configuration) | [Licence](#licence) | [Publications](#publications) | [Contributing](co
```suggestion
| [How to use](#How-to-use) | [Installation](#installation) | [Tutorials and Examples](#tutorials-and-Examples) | [Contributing](contributing.md) | [Licence](#licence) | [Citation](#citation) |  |
```

2022-05-17 12:48 UTC, bobturneruk commented
Preview docs here https://topostats.readthedocs.io/en/better-docs/

2022-05-17 13:03 UTC, ns-rse approved these changes
The Markdown inline `mark-up` hasn't carried through to the ReadTheDocs HTML for some reason but that is minor and can be corrected in due course.

2022-05-18 11:46 UTC, SylviaWhittle approved these changes
Looks very good - I'll update the 'how it works' to reflect what is done in `topotracing.py` and `grainstats.py` after this pull.

2022-05-18 11:55 UTC, merged