Document config file options
AFM-SPM/TopoStats pull request #200
Opened 2022-07-11 10:56 UTC by bobturneruk

2022-07-11 11:06 UTC, ns-rse reviewed
One issue with regards to default behaviour which hasn't yet been implemented but I think it should be, otherwise looks good. Thanks @bobturneruk

2022-07-11 11:18 UTC, bobturneruk commented on docs/configuration.md
> +If no configuration YAML file is found while running TopoStats, it will generate a default file.
Cheers @ns-rse - helps with my understanding of what the software does, too.

2022-07-27 11:07 UTC, bobturneruk commented
This is ready for some feedback. There are a few TBDs which by pooling the team's knowledge we should be able to fill in. And I've made some assumptions which are probably wrong. If anyone would like to take this branch and edit it directly, please feel free to, but leave a comment here so we know who has it.

2022-07-28 08:25 UTC, MaxGamill-Sheffield requested changes
Some changes with wording but otherwise it looks good. 

Is there also a way to see this with the markdown applied?

2022-07-28 08:25 UTC, MaxGamill-Sheffield commented on docs/configuration.md
> +| `base_dir` | The directory (folder) in which the software should search for images to analyse. | `./tests/` | Path. |
maybe add "recursively search"

2022-07-28 08:25 UTC, MaxGamill-Sheffield commented on docs/configuration.md
> +| `output_dir` | The directory (folder) in which output should be saved. | `./output` | Path. |
"outputs" or "the output" (sorry to be pedantic)

2022-07-28 08:25 UTC, MaxGamill-Sheffield commented on docs/configuration.md
> +| `save_plots` | Should plots be saved? | `true` | `true` or `false` |
This and line 90 seem very similar. This is good for now but maybe we need to think about condensing the config file and avoid confusion in the future, and check what each of these do?

2022-07-28 08:25 UTC, MaxGamill-Sheffield commented on docs/configuration.md
> +| `gaussian_size` | The standard deviation of the Gaussian kernel used to filter grain sizes | 2.0 | Any positive real number. |
is the standard deviation value in pixels or nm?

2022-07-28 08:25 UTC, MaxGamill-Sheffield commented on docs/configuration.md
> +| `zrange` | The height of the the highest and lowest objects under analysis. | [0, 3] | A list of two real numbers. |
I think this makes it sound like the user should be guessing the heights of things in their images. 
Maybe "Assigns values outside the low and high boundaries to the boundary values (purely aesthetic)".

2022-07-28 08:25 UTC, MaxGamill-Sheffield commented on docs/configuration.md
> +| `mask_direction` | *TBD* | `upper` | String `upper` or `lower`. |
"Direction to apply masking, above the surface or below the surface." maybe?

2022-07-28 09:53 UTC, bobturneruk commented
Thanks for the feedback @MaxGamill-Sheffield - the "rich diff" may be what you're looking for to see the document rendered as markdown https://github.com/AFM-SPM/TopoStats/pull/200/files?short_path=17ed184#diff-17ed18489a956f326ec0fe4040850c5bc9261d4631fb42da4c52891d74a59180

The docs can be built locally using:
```
pip install -e .[docs]
cd docs
make html
```

I'll have a look at the specific feedback soon.

2022-08-05 12:50 UTC, bobturneruk commented
I suggest work here is paused until progress is made on https://github.com/AFM-SPM/TopoStats/issues/255

2022-10-11 17:54 UTC, ns-rse commented
#255 has been resolved and #307 includes another attempt at documenting the configuration file options so I'm closing this PR.

It will be important as we progress that this documentation is kept up-to-date with changes in the code.

2022-10-11 17:54 UTC, closed without merging