Maxgamill sheffield/224 mask overlay image
AFM-SPM/TopoStats pull request #229
Opened 2022-07-20 12:47 UTC by MaxGamill-Sheffield

This should now create an image combining the z-thresholded image and the upper/lower (you choose in the config) removed_small_objects grains. Additionally it includes a test that checks the produced image hasn't changed.

The config addition was added into 'Grains' because Alice mentioned she wanted this as a config option instead of producing both upper and lower grains when only one might be needed. Although this has not been implemented here, it may be useful for when it is implemented.

Here when 'upper' is specified in the config:
![Screenshot 2022-07-20 at 13 44 08](https://user-images.githubusercontent.com/91465918/179985042-335886d1-b070-4372-a77d-774d0b7a86ef.png)

And here is 'lower':
![Screenshot 2022-07-20 at 13 40 30](https://user-images.githubusercontent.com/91465918/179984327-0a6516d8-2552-4104-8d55-d18fc92c6df8.png)

2022-07-20 12:51 UTC, MaxGamill-Sheffield commented
Closed and re-opened because I initially tried to pull to master and after swapping to dev, the tests didn't initiate. 
Now they have done.

2022-07-22 10:18 UTC, ns-rse commented on topostats/run_topostats.py
> +    "mask_overlay": {"filename": "13_5-mask_overlay.png", "title": "Hight Thresholded with Mask", "type": "non-binary"},
Typo
```suggestion
    "mask_overlay": {"filename": "13_5-mask_overlay.png", "title": "Height Thresholded with Mask", "type": "non-binary"},
```

2022-07-22 10:51 UTC, ns-rse requested changes
Just a typo, but otherwise good to go, thanks again for getting this done so quickly.

2022-07-22 11:44 UTC, ns-rse approved these changes
All good to go :+1:

2022-07-22 11:45 UTC, merged