Maxgamill sheffield/224 output file dir structure
AFM-SPM/TopoStats pull request #231
Opened 2022-07-21 11:46 UTC by MaxGamill-Sheffield

This PR orders the output directories into a structure similar to how the files are found.

Here, using "./data/" as the `base_dir` in the config file, we have multiple directories containing multiple files, i.e:
<img width="962" alt="Screenshot 2022-07-21 at 12 41 14" src="https://user-images.githubusercontent.com/91465918/180205295-159d4f45-3a5d-4bb9-a82e-8af8c1c7ee7b.png">

The PR replaces the `base_dir` of the `image_path` with the `output_dir`, keeping the subsequent directory structure after.
This creates an output mirroring the inputs, i.e:
<img width="1210" alt="Screenshot 2022-07-21 at 12 43 36" src="https://user-images.githubusercontent.com/91465918/180205736-56f5b489-0a72-4c35-a586-1708594bf911.png">

Further work will be done to remove the `minicircle<#>` directories but this should only happen after:
1) The output files are truncated.
2) The output files are re-named to reflect the file they originated from
In order to avoid overwriting output files.

2022-07-21 13:35 UTC, MaxGamill-Sheffield commented
Apologies for the post PR commit. I realised I could obtain the output path faster by not using for loops

2022-07-21 13:37 UTC, bobturneruk commented
Fine by me! Might as well make things better where there's an opportunity, and it hasn't been reviewed!

2022-07-22 10:31 UTC, ns-rse commented on topostats/utils.py
> +def get_out_path(image_path: Union[str, Path] = None, base_dir: Union[str, Path] = None, output_dir: Union[str, Path] = None):
You can add a return type here...

```suggestion
def get_out_path(image_path: Union[str, Path] = None, base_dir: Union[str, Path] = None, output_dir: Union[str, Path] = None) -> Path:
```

2022-07-22 10:40 UTC, ns-rse requested changes
Thanks for getting this done so quickly Max, one very minor addition of a return type hint.

2022-07-22 11:44 UTC, ns-rse approved these changes
Also good to go :+1:

2022-07-22 11:45 UTC, merged