13 fix unclear comments in dnatracing
AFM-SPM/TopoStats pull request #25
Opened 2021-01-25 15:54 UTC by JoeBeton

I edited the vague/totally useless comments in getFittedTraces() - would be good to know if the new comments are clear enough for others to understand. Can improve/clarify comments further if necessary.

2021-01-25 15:57 UTC, bobturneruk commented
If I write resolves #24, then issue 24 will be automatically closed when this is merged!

2021-02-06 18:37 UTC, Jean-Du commented on dnatracing.py
> +                                                        index_width:
Move this to the line above?

2021-02-06 18:38 UTC, Jean-Du commented on dnatracing.py
> +                                                        index_width
Again, should this be moved to the line above?

2021-02-06 18:41 UTC, Jean-Du commented on dnatracing.py
> +                            self.gauss_image[perp_array[:,1], perp_array[:,0]]
Why is this put into two lines?

2021-02-06 18:46 UTC, Jean-Du requested changes
There are a few occasions where one line seems to be separated into two; was this intended?
Also regarding line 315, "can delete", is this part still used by the code? Might want to test by commenting it out and see if it still works before saying it can be deleted

2021-02-08 09:22 UTC, JoeBeton commented
> 
> 
> There are a few occasions where one line seems to be separated into two; was this intended?
> Also regarding line 315, "can delete", is this part still used by the code? Might want to test by commenting it out and see if it still works before saying it can be deleted

Python style guide (PEP 8) specified a maximum line length of 79 characters. Not the biggest issue in the world but does make the code more readable if the reader doesn't have to horizontally scroll to see a full line of code. 

See specific part of Python style guide here: https://www.python.org/dev/peps/pep-0008/#maximum-line-length

2021-02-08 10:24 UTC, Jean-Du approved these changes

2021-02-08 10:25 UTC, merged