Sylvia whittle/404 grainstats crash
AFM-SPM/TopoStats pull request #454
Opened 2023-02-08 12:23 UTC by SylviaWhittle

Tiny PR! 

Closes #404 

This PR aims to fix bug #404, by both preventing tiny grains (less than 5x5) being processed in grainstats, and also to improve the edge finding algorithm so that if in future we want to handle grains less than 5x5, `calculate_edges` will be able to handle this. (Note that other functions may still have issue with this). So in effect, this *should* be both prevention and cure for the bug. 

I have verified that this works locally on my machine, however for you to verify that it fixes the bug, run latest `main` TopoStats on this file: https://drive.google.com/drive/folders/1jAkiS0KKLBmOw8rKLZ-nrgy4MIhfyoJT (let me know if you need permissions to access), with this config:

```yaml
base_dir: ./
output_dir: output
warnings: ignore
cores: 2
quiet: false
file_ext: .spm
loading:
  channel: Height
filter:
  run: true
  threshold_method: std_dev
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.3
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  gaussian_size: 1.0121397464510862
  gaussian_mode: nearest
  remove_scars:
    run: true
    removal_iterations: 2
    threshold_low: 0.25
    threshold_high: 0.666
    max_scar_width: 4
    min_scar_length: 16
grains:
  run: true
  threshold_method: std_dev
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.3
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  direction: upper
  smallest_grain_size_nm2: 10
  absolute_area_threshold:
    upper:
    - 10
    - 100000
    lower:
    - 
    - 
grainstats:
  run: true
  cropped_size: 40.0
dnatracing:
  run: true
plotting:
  run: true
  save_format: png
  image_set: core
  zrange: [-3, 4]
  colorbar: true
  axes: true
  cmap: nanoscope
  mask_cmap: blu
  histogram_log_axis: false
  histogram_bins: 200

```

For me, this fixes the issue, allowing another bug (#402 ) to occur, but that is for me to fix next 😄 

Snippet:
```bash
[Wed, 08 Feb 2023 12:20:39] [INFO    ] [topostats] [E4-24h-nm.0_00006] : *** DNA Tracing ***
[Wed, 08 Feb 2023 12:20:39] [INFO    ] [topostats] [E4-24h-nm.0_00006] : Gaussian filter applied.
Processing images from /Users/sylvi/topo_data/404-grainstats-crash, results are 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sylvi/Documents/TopoStats/topostats/run_topostats.py", line 334, in process_scan
    dna_traces[direction].trace_dna()
  File "/Users/sylvi/Documents/TopoStats/topostats/tracing/dnatracing.py", line 91, in trace_dna
    self.get_splined_traces()
  File "/Users/sylvi/Documents/TopoStats/topostats/tracing/dnatracing.py", line 415, in get_splined_traces
    while nbr / step_size < 4:
ZeroDivisionError: division by zero
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/bin/run_topostats", line 8, in <module>
    sys.exit(main())
  File "/Users/sylvi/Documents/TopoStats/topostats/run_topostats.py", line 442, in main
    for img, result in pool.imap_unordered(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
ZeroDivisionError: division by zero
```

I have decided not to make this 5x5 option configurable, as I don't think this is a user-facing option, since it is inherently tied to the processing limitations and allowing users to ignore or change this check could break things for them. However, that being said, please do say if you think this is unwise.

2023-02-08 13:33 UTC, SylviaWhittle commented
I have updated the regtests, these updates are minor and accounted for. 

The previously used method for detecting edges of a grain, using `canny` filtering, produced smoothed edges, which are not completely accurate, but good approximations. The updated method using erosion reliably produces exact edges. Here is an example:

![image](https://user-images.githubusercontent.com/86117496/217544241-c8bed439-2f0b-4392-978f-a29778f125f9.png)

LHS: Grain mask
Mid: Old canny edge-finding
RHS: New erosion edge-finding

2023-02-08 15:19 UTC, ns-rse commented on topostats/grainstats.py
> +            if min(region.image.shape) < 5:
Good to see you caught my dumb mistake!

2023-02-08 20:32 UTC, ns-rse reviewed
Looks ok code wise to me.

I can't really comment on the difference between [`canny`](https://scikit-image.org/docs/dev/auto_examples/edges/plot_canny.html) v [`erosion`](https://scikit-image.org/docs/stable/api/skimage.morphology.html#skimage.morphology.erosion) for defining boundaries though (I see there is also [`binary_erosion](https://scikit-image.org/docs/stable/api/skimage.morphology.html#skimage.morphology.binary_erosion) which does the same but faster, perhaps worth considering if at this point erosion is done on a binary image :shrug: ). `canny` used a fixed value of `sigma=3` so perhaps this might have been something that was configurable by users and might have made a difference?

For example the `canny` method gives smooth edges which might not be accurate, but then @Jean-Du has introduced a splining method to DNA Tracing which is, based on my crude understanding, also a method of smoothing curves. What is the preferred method _overall_? (That is a rhetorical question though and I actually think giving people options to choose what works best for them is preferable).

Approving but perhaps we need to give some thought as to what we want to use/make available. We could perhaps consider making the method (`canny` v `erosion` v `binary_erosion`) configurable so that users are able to choose what is best for them.

2023-02-08 21:00 UTC, SylviaWhittle commented
Thank you @ns-rse . Those are some excellent points. 

I will field the options to the experimentalists in a meeting tomorrow morning to see what would be preferable and if they would like the option of `canny` edge detection. I would guess that accuracy at the grainstats stage is imperative given that small changes in statistics like `min_feret` are used in research to determine effectivenesses of different therapeutics.

You are right about `binary_erosion`, I have updated that accordingly.

Perfectly happy to wait for #455 before merging 👍

2023-02-10 12:01 UTC, MaxGamill-Sheffield commented
I was just thinking about this - is there a reason these tiny 5x5 grains aren't removed by the "absolute smallest grain size". And should this then be a value in pixels of this limit, to ensure the edge detection works?

I also prefer the mask-edge accuracy of the `erosion` method, although both `erosion` and `canny` methods require accurate molecule masks to produce accurate statistics, and `canny` may help to alleviate this (testing needed).

2023-02-10 12:15 UTC, SylviaWhittle commented
@MaxGamill-Sheffield So 5x5 grains are not usually encountered, unless the user sets the size thresholding values to really low (like I accidentally did at one point while processing Raphael's data, which is how this bug was found).

I don't think this should be a size defined in nanometres, since it's a limitation directly tied to pixel size (`canny` cannot process less than 5x5 correctly), not the real-world length scale. If it was tied to nanometres, then images with different `pixel_to_nm_scaling_factor`s might trigger this issue again.

Given the helpful feedback, I think I might keep both methods in, and have a default of `erosion`. What do you both think of this?

2023-02-13 12:19 UTC, ns-rse requested changes
One very minor modification to `docs/configuration.md` but otherwise good to go. :+1:

2023-02-13 13:38 UTC, ns-rse approved these changes
On :fire: ! More than happy to approve.

2023-02-13 13:43 UTC, merged