Makes DPI configurable via default_config.yaml
AFM-SPM/TopoStats pull request #527
Opened 2023-04-14 15:08 UTC by ns-rse

Closes #526

The `Images` class always had `dpi` as an option but it was not accessible from `run_topostats` as no options were present in the configuration file and therefore didn't cascade through. Dots Per Inch (DPI) can now be specified in the configuration file, its default is set to `100.0` (the default used by `savefig` in Matplotlib). Validation is performed and a test introduced that sets `dpi = 300` for testing to check the value cascades through and plots are made using this value (this also required setting the parameter for the `pytest-mpl` fixture too, otherwise it would save the figure with the default value).

2023-04-14 16:49 UTC, SylviaWhittle requested changes
Minor typo.

Also, I may be misunderstanding, but there seems to be no code here to set the DPI for output figures, only for `test_high_dpi()`? Is this intended?

2023-04-14 16:49 UTC, SylviaWhittle commented on topostats/validation.py
> +                lambda n: n > 0, "figure", error="Invalid valud in config for 'dpi', valid values are 'figure' or > 0."
```suggestion
                lambda n: n > 0, "figure", error="Invalid value in config for 'dpi', valid values are 'figure' or > 0."
```

2023-04-17 09:13 UTC, ns-rse commented on topostats/validation.py
> +                lambda n: n > 0, "figure", error="Invalid valud in config for 'dpi', valid values are 'figure' or > 0."
You weren't mistaken, I corrected it.

2023-04-17 09:52 UTC, ns-rse commented
> Just to check...
> 
> I tried running topostats with dpi=1 and it produced exactly the same image as dpi=1000. Is this normal?

That isn't what I'd expect, and sorry for not checking.

I've investigated and realised that I'd forgotten how we pass options to each image (via the `plot_dict` key/value of `plotting_config`). In doing so we update each of these nested dictionaries with the plotting options and I hadn't added `dpi` to this list.

I've therefore modified how this is done in the `update_plotting_config()` function so that in the future new options that are added won't require explicit inclusion, they will be passed through automatically thanks to `**kwargs` expansion (see [27be2fbb](https://github.com/AFM-SPM/TopoStats/pull/527/commits/27be2fbb7109e155dd7c36e85f5c17c37670d0a5) for the specific change if curious).

Thanks for catching this, a glaring omission on my behalf :blush: but hopefully an improved solution.

2023-04-17 13:54 UTC, SylviaWhittle commented on topostats/utils.py
> +        plotting_config["plot_dict"][image] = {**options, **main_config}
Very elegant! Thanks for the improvement.

2023-04-17 14:12 UTC, MaxGamill-Sheffield commented
I just wanted to clarify behaviour for this. So the dpi was originally put into the images class in preparation for DNAtracing to produce visible single pixel traces with the intention to set these at the plottingdict level.

So my question is if this is now a config parameter, have we given any thought to handling different images separately? On my cats branch where I've implemented this it takes a while to produce a single plot at 1000 dpi (to show representitive skeletons / traces although I've not seen how low of a dpi I could go), so if all 20 plots are set globally like this are we concerned with runtime?

2023-04-17 14:41 UTC, SylviaWhittle commented
> I just wanted to clarify behaviour for this. So the dpi was originally put into the images class in preparation for DNAtracing to produce visible single pixel traces with the intention to set these at the plottingdict level.
> 
> So my question is if this is now a config parameter, have we given any thought to handling different images separately? On my cats branch where I've implemented this it takes a while to produce a single plot at 1000 dpi (to show representitive skeletons / traces although I've not seen how low of a dpi I could go), so if all 20 plots are set globally like this are we concerned with runtime?

@MaxGamill-Sheffield Good point. I suppose that this is the base functionality, and in a new issue / PR, we could add the ability to only let it affect the two main output plots?

2023-04-17 14:51 UTC, merged