Only create filters, grains dirs when image_set is "all"
AFM-SPM/TopoStats pull request #558
Opened 2023-05-11 15:39 UTC by SylviaWhittle

Closes #541 

Adds simple checks to ensure that the `filters` and `grains` directories are only created when `image_set` is `"all"`.

I can't imagine this having any conflicts, and I tried running TopoStats a few times with various configurations including `image_set: "core"` and `image_set: "all"`, but I could have missed something.

2023-05-11 16:03 UTC, SylviaWhittle commented on topostats/processing.py
> +    if plotting_config["image_set"] == "all":
Thanks! Done 👍

2023-05-12 10:36 UTC, ns-rse requested changes
Tests fail, I think I've clocked why, sorry for my mistake.

2023-05-12 10:36 UTC, ns-rse commented on topostats/processing.py
>      filter_out_path = core_out_path / filename / "filters"
To fix the tests which currently fail we need to move the

```python
grain_out_path = core_out_path / filename / "grains"
```

to here, but leave all the `*.mkdir()` calls within the `if plotting_config["image_set"] == "all":`

Apologies for not clocking/understanding/testing this in my original suggestion/comment.

2023-05-12 18:27 UTC, ns-rse reviewed
Looks ready to go. :+1:

2023-05-12 18:27 UTC, ns-rse approved these changes

2023-05-12 18:28 UTC, merged