Add .asd file support
AFM-SPM/TopoStats pull request #675
Opened 2023-09-28 17:44 UTC by SylviaWhittle

This PR adds support for loading `.asd` files into TopoStats, processing all the frames automatically and saving each frame as an individual image output.

This is not going to be the final workflow for `.asd` files, however I want to split this task up into smaller PRs to get feedback from users on how it should be improved going forward.

The actual loading of the `.asd` file is done using my `[topofileformats](https://github.com/AFM-SPM/topofileformats)` package that I wrote to decode and load `.asd` files into numpy arrays.

[Technical details]
- I have added a test for loading `.asd` files.
- I had to change how files are added to the image dictionary in `io.py` as now each file might have more than one image. I hacked this in by checking the file extension and if it's `.asd` then iteratively add all the frames. Far from tidy, would welcome suggestions on better methods.

2023-11-02 10:15 UTC, SylviaWhittle commented
This implementation uses **a lot** of RAM. I ran a 57mb .asd file and it used about 2GB of RAM with grains, grain stats and dnatracing disabled. It would be a lot more with those enabled.

Note to self: is there a way to free memory in between frames being processed?

2023-11-06 22:15 UTC, SylviaWhittle commented
The RAM issue seems to be okay actually. While it does use a lot of RAM, it does not increase when running with image set `all` and maintains its stability at 2GB of RAM. This is reasonable given the weight of the files being asked to process.

2023-11-10 08:27 UTC, ns-rse requested changes
Looks good @SylviaWhittle I like that you've moved a lot of the leg-work to its own package in [`topofileformats`](https://github.com/AFM-SPM/topofileformats/) (hope you don't mind I've added myself as a collaborator on that project and started looking through the code).

Some comments in line.

2023-11-10 08:27 UTC, ns-rse commented on tests/test_io.py
> +    CONFIG_PATH = {
Curious what linter (`black` or `ruff>=0.1.4`-ish) have decided to wrap these lines as they and others in this file are all <120. :thinking:

2023-11-10 08:27 UTC, ns-rse commented on tests/test_io.py
> +    print(scan.img_dict)
Errant debug `print()`.

Surprised `ruff` doesn't pick this up (see [print (T201)](https://docs.astral.sh/ruff/rules/print/)) either locally 
when running the `pre-commit` hook or here on when `pre-commit.ci` runs.

I'll look into that as we've had to explicitly disable this in `tests/test_processing.py` where `pytest.regtest` requires a `print()` statement to write the CSV files for the regression tests.

2023-11-10 08:27 UTC, ns-rse commented on tests/test_io.py
> +    load_scan_spm._check_image_size_and_add_to_dict(image=load_scan_spm.image, filename=load_scan_spm.filename)
Good spot, presumably this test wasn't doing anything or failed in some manner?

2023-11-10 08:27 UTC, ns-rse commented on topostats/io.py
>          """Check the image is above a minimum size in both dimensions.
I think its useful to explain the action taken in light of the check.

```suggestion
        """Check the image is above a minimum size in both dimensions. If not the image is not processed further.
```

2023-12-19 11:30 UTC, ns-rse commented on tests/conftest.py
> +    return LoadScans([RESOURCES / "file.asd"], channel="TP")
2023-12-19 - Only these three channels are known about.

2023-12-19 11:30 UTC, ns-rse commented
Three different standards for different ASD files, 0, 1 and 2, only have test files for 0 and 1 but not 2.

2023-12-19 11:55 UTC, ns-rse commented
@ns-rse to round out.

2023-12-19 12:22 UTC, ns-rse approved these changes
All comments addressed (most were just that and didn't require any changes and one was redundant I'd just not read the subsequent line).

Removed errant `print()` I'm unsure why `ruff` didn't pick this up (either locally or via `pre-commit.ci` as [T201](https://docs.astral.sh/ruff/rules/print/) should have complained about its presence and the file isn't explicitly excluded.

Otherwise good to go.

2023-12-19 12:29 UTC, ns-rse approved these changes
Good to go, can I approve having now contributed though? :thinking:

2023-12-19 12:31 UTC, merged