Add a zeroing step to filters
AFM-SPM/TopoStats pull request #688
Opened 2023-10-06 20:36 UTC by SylviaWhittle

This PR is just to add a height zeroing step before masking, as previously using an absolute threshold on **some** images was being affected by the image being too high up / low down and not centred on its average height. This is mostly a "just in case" step that doesn't add any time to the overall computation time of `filters.py`.

2023-10-06 21:19 UTC, SylviaWhittle commented
CodeCov doesn't seem to like me removing the logging lines... Apparently removing lines reduces coverage?

2023-10-08 11:06 UTC, ns-rse requested changes
Baffled why the coverage changes removing logging statements.

Not sure if we should be switching the `image_set: all` in `topostats/default_config.yaml` as it introduces lots of additional processing time.

2023-10-08 18:54 UTC, SylviaWhittle commented on topostats/default_config.yaml
> +  image_set: all  # Options : all, core
This was accidental. I missed it when sanity checking my PR, sorry! Reverted

2023-10-08 18:58 UTC, SylviaWhittle commented on topostats/validation.py
Yeah I'll look at my local / pre-commit black settings to see if there's a difference.

2023-10-08 19:02 UTC, SylviaWhittle commented on topostats/plotting.py
> -        LOGGER.info(f"melted data: \n {self.melted_data}")
Do you know how to get around this issue? I don't necessarily think these lines are particularly useful.

Here is a post talking about it but with no resolutions yet: https://community.codecov.com/t/project-coverage-decrease-on-deleted-line/2726/3

It technically is a decrease in coverage as removing covered lines will decrease the proportion. Perhaps not allowing PRs that decrease coverage is not useful and instead we ensure that all added lines are covered?

2023-10-09 12:47 UTC, ns-rse approved these changes
Thanks for fixing up `default_config.yaml` :+1:

2023-10-09 12:47 UTC, ns-rse commented on topostats/plotting.py
> -        LOGGER.info(f"melted data: \n {self.melted_data}")
I'm not convinced its an issue with removing lines, rather that they should not have been included in the coverage anyway as unless we have a specific test that checks for the output in the logs there is no coverage of those lines. Its a false positive so happy for this to be merged.

2023-10-10 11:23 UTC, merged