Sylvia whittle/height trace redo
AFM-SPM/TopoStats pull request #695
Opened 2023-10-12 16:45 UTC by SylviaWhittle

Adds the option of saving grain trace heights & grain trace cumulative distances to JSON file.

Trace heights mean the pixel heights of every coordinate in the ordered trace. It is an array / list.

Trace cumulative distances are the distances for each pixel as you traverse the ordered trace. Distances only go up by 1.0 or sqrt(2) since pixels are either adjacent or diagonal. Hope that makes sense.

They are saved in files like this:

![image](https://github.com/AFM-SPM/TopoStats/assets/86117496/47007e8a-6526-46b8-b39b-c4479e757634)

The structure of the JSON is a dictionary where the keys are the molecule number and the values are the lists of data (heights or cumulative distances).

[Technical notes]

Internally I kept the arrays as lists, since JSON cannot serialise numpy arrays, and I thought it would be preferable to avoid adding a script to deconstruct the dictionary, then convert the arrays to lists and then re-constructing the dictionary again. Let me know if this is silly 😋 

I have kept the saving in `processing.py` as I plan for `run_topostats` to be generic and not handle extra output from workflows in the future. Feel free to disagree with me on this, but I think maybe we should let workflows save data as they see fit during processing of individual images without them having to return it to `run_topostats` since I foresee workflows saving **a lot** of random stuff that we don't necessarily want to write extra code to handle in `run_topostats`?

2023-10-16 10:54 UTC, SylviaWhittle commented
Adding a test for the `.json` output is blocked by #653

2023-10-17 19:06 UTC, ns-rse commented
Not looked at the code yet, and this may be part of the JSON output but there's no test to see what it looks like (sorry for banging the same :long_drum: again) but I'm wondering what the utility of knowing the heights without the locations is?

Sure summary statistics could be calculated, but if anyone wanted to plot or visualise the data elsewhere the location of the points would be required.

2023-10-25 08:02 UTC, ns-rse commented
> I have kept the saving in `processing.py` as I plan for `run_topostats` to be generic and not handle extra output from workflows in the future. Feel free to disagree with me on this, but I think maybe we should let workflows save data as they see fit during processing of individual images without them having to return it to `run_topostats` since I foresee workflows saving a lot of random stuff that we don't necessarily want to write extra code to handle in `run_topostats`?

I agree with this, each module of analysis should save whatever it should/is configured to do at each stage.

2023-11-02 09:09 UTC, SylviaWhittle commented
No longer blocked by #653

2024-01-24 10:13 UTC, SylviaWhittle commented
Put all stats into one file with image and grain number as the index. Also rename the index to a string of "grain_54" etc instead of "54"

2024-01-24 10:50 UTC, SylviaWhittle commented
There has been some debate about what format the files should be saved in, and if all traces should be in one file or multiple etc, and so I'm thinking before trying to refine this further, push to main and let people use it for a while to see what issues come up?

Happy to change how this works if people feel strongly on it though. Just this has been delayed due to indecision and also me not being available enough 😅

2024-01-24 11:07 UTC, ns-rse commented
:+1: Yes, definitely isolate the code into its own testable function. Test with small examples rather than full data set if possible too (even smaller than the cropped picture is likely possible, see examples of tests for `write_yaml()` in [`tests/test_io.py::test_write_config](https://github.com/AFM-SPM/TopoStats/blob/43410ab06bf366764271553a16f88d97f3c29999/tests/test_io.py#L116) which uses a dummy [`CONFIG`](https://github.com/AFM-SPM/TopoStats/blob/43410ab06bf366764271553a16f88d97f3c29999/tests/test_io.py#L39)).

2024-01-24 13:16 UTC, SylviaWhittle commented
Note to self: Make the heights and distances all in one JSON and change molecule index to a string "grain_54".

2024-01-29 13:34 UTC, ns-rse commented on temp_json_experiment.ipynb
This Notebook can probably be removed.

2024-01-29 14:20 UTC, ns-rse requested changes
Some comments in line but one thought that occurred to me whilst reviewing is whether we are creating additional boiler plate data for a very specific function.

The `.topostats` file which is used for saving results to uses HDF5 which is a very similar structure to JSON in terms of nested data. Would it not save us a large amount of work to have the height trace data saved to the HDF5 if people need to access it?

I'm also not sure about whether JSON is the best format for people to use (something we've discussed before) as its unfamiliar to many who are used to columnar/tabular data and this data itself isn't highly nested in nature.

2024-01-29 14:20 UTC, ns-rse commented on topostats/default_config.yaml
> +  save_trace_json_data: false # Whether to save things such as height traces to JSON files.
Would you be able to add an equivalent row into `docs/configuration.md` for this new option please? :pray:

2024-01-29 14:20 UTC, ns-rse commented on topostats/tracing/dnatracing.py
> +        # Get the heights of each pixel in the ordered trace from the gaussian filtered image
Comment is redundant as the docstring should contain this information.

2024-01-29 14:20 UTC, ns-rse commented on topostats/tracing/dnatracing.py
> +        return list(np.asarray(cumulative_distance_list) * px_to_nm)
No need to convert to an array as can just use list comprehension
```suggestion
        return [distance * px_to_nm for distance in cumulative_distance_list]
```

2024-01-29 14:20 UTC, ns-rse commented on topostats/tracing/dnatracing.py
> +        return list(np.asarray(cumulative_distance_list) * px_to_nm)
Also does this make redundant the `recursive_numpy_array_to_list()` function if as noted `Better to do the conversion here than have to do it in the JSON saving script`?

2024-08-02 09:22 UTC, closed without merging