reduced max trace coord idx by 1 so within image bounds
AFM-SPM/TopoStats pull request #752
Opened 2023-12-07 20:57 UTC by MaxGamill-Sheffield

fixes #751

Ensures that if the max fitted coord looks outside the image, it's max is the end of the image. 

Previously this matched the max shape of the array i.e. arr.shape=(10,10), but index was set to 10 which is outside the max index.

Seems like it was only an issue now because Eddie's images are very zoomed in and the `index_width` was set to 3nm which is quite a few pixels and exceeds the padding value of 1.

2023-12-11 16:06 UTC, ns-rse commented
Tests fail as the arrays have changed in size.

The problem arises here because the scaling value is `0.5859375` and so `index_width` is set to `2` (as per line 238/239). One of the grains is very close to the edge and so the bounding area for `x_coords` and `y_coords` calculated somewhere between rows 275-304 conditional on the value of `vector_angle` can result in co-ordinates outside of the image.

However, I've been trying to reason through these conditional statements and make sense of them. I've removed the original comments and added my own in the code chunk below rather than as separate comments in the changed file as some (e.g. the first comment) can't be commented on in the file in the PR as it lies outside of the permissible range.

```python
            # Will a trace co-ordinate ever be negative? It is by definition a 
            # co-ordinate of the trace within the image so should always be >= 0
            # Perhaps the inequality should be 
            #
            # if trace_coordinate - index_width < 0:
            if trace_coordinate[0] < 0:
                trace_coordinate[0] = index_width
            elif trace_coordinate[0] >= (self.number_of_rows - index_width):
                trace_coordinate[0] = self.number_of_rows - index_width - 1
            # I don't think this should be elif as it would only ever be reached if
            # the previous two conditions are False, yet since the second co-ordinate 
            # is the column position the check should be made independent of the first 
            # co-ordinate (which refers to row) that is handled above, and as with above
            # I think the inequality here can never be met since this value will always 
            # be >= 0 so it should perhaps be
            #
            # if trace_coordinate[1] - index_width < 0:
            #           
            # As this will always be checked regardless of the value of `trace_coordinate[0]`
            # and what changes have been made above.
            elif trace_coordinate[1] < 0:
                trace_coordinate[1] = index_width
            elif trace_coordinate[1] >= (self.number_of_columns - index_width):
                trace_coordinate[1] = self.number_of_columns - index_width - 1
```

Would be interested to know others thoughts on these two issues which are

1) `trace_coordinate[0|1] < 0` is never met since co-ordinates are always `>= 0`.
2) The column co-ordinate (`trace_coordinate[1]`) should always be assessed independent of the row co-ordinate.

I didn't clock these 6 months ago when refactoring `dnatracing.py` to work with individual grains as my focus was on removing the many loops that iterated over all the grains.

2023-12-14 10:26 UTC, ns-rse requested changes
Solves the problem but I'm unsure why this should change the size of the resulting arrays (the cause of the failing test).

I've made some comments around the general logic of this chunk of code that should probably be addressed whilst work is being undertaken to avoid future problems.

2023-12-14 11:04 UTC, MaxGamill-Sheffield commented
So my initial thought was that because `number_of_rows` and `number_of_columns` come from the `np.ndarray.shape` property, the index of this would be off by 1 when indexing. 

i.e. with a shape of (10,10), the variables `number_of_rows` etc would be 10 but only be indexed upto 9. Thus if the coord value satisfied:
`trace_x >= (self.number_of_rows - index_width)`, the value cannot be set to `self.number_of_rows - index_width` as the diagonals would exceed the bounds. If `index_width=0`, condition: `trace_x >= self.number_of_rows` >> `trace_x = self.number_of_rows` and x would exceed the index bounds.

I agree that the coords should not be < 0.

And for 2. Yes I very much agree.

2023-12-19 16:22 UTC, ns-rse approved these changes
Thanks for taking the time to review and incorporate my suggestions with regards to the logic used for bounding on the right side of the image @MaxGamill-Sheffield.

The tests may seem excessive but they demonstrate that we now definitely do achieve what we want to as this bug had gone unnoticed since the code was written. I expect this is because previously the whole image was processed as one and grains were never observed that close to the boundary, now that we crop grains prior to tracing this occurs more frequently.

This is good to go.

2023-12-22 01:04 UTC, merged