tests(ordered_tracing): Tests and fixes for ordered_trace_mask()
AFM-SPM/TopoStats pull request #885
Opened 2024-08-12 16:18 UTC by ns-rse

The function `ordered_trace_mask()` looked strange on review...

- Docstring said it took `npt.NDArray` as argument but logic only returned mask if `list` was supplied.
- Slicing caused `TypeError: list indices must be integers or slices, not tuple`.
- After correcting that `np.arange(len(mol_coords))` raised a `ValueError: setting an array element with a sequence.`

Test written to demonstrate these problems and alternative `trace_mask()` function offered (along with tests that pass).

2024-08-12 16:26 UTC, ns-rse commented
Noticed there are still pre-commit errors raised in CI on files I've not touched in this PR that should be addressed before the target branch is merged into `main`. Details [here](https://results.pre-commit.ci/run/github/168173540/1723479526.C8HXLAODRaabdNXZyGKrBQ) for reference.

2024-08-13 11:00 UTC, ns-rse commented
It is worth noting though that there is currently a `pylint` error for `unused-variable` pertaining to the returned
`graint_trace_data`...

```
************* Module topostats.processing
topostats/processing.py:999:20: W0612: Unused variable 'grain_trace_data' (unused-variable)
```

...which will need dealing with.

2024-08-13 16:12 UTC, MaxGamill-Sheffield requested changes
Hey Neil, great work thanks for looking at this! As in the comments, I'm happy for your function to be used instead of `ordered_trace_mask` (although I think it should keep this name).

However, the reason for handing the function lists was to parse a list of different length Nx2 coordinate arrays, and for these arrays to be plotted in ascending integer values to see the direction of tracing, and so I've suggested some changes to your function (but not the tests). 

Let me know if that makes sense :)

Binary mask:
<img width="201" alt="Screenshot 2024-08-13 at 17 09 47" src="https://github.com/user-attachments/assets/53d77669-9aeb-493a-9dfc-b96971cba7b0">
Ordered trace mask:
<img width="346" alt="Screenshot 2024-08-13 at 17 11 27" src="https://github.com/user-attachments/assets/17e75661-18e2-44aa-95b6-3707749869ac">

2024-08-13 16:12 UTC, MaxGamill-Sheffield commented on topostats/tracing/ordered_tracing.py
> +            mask[mol_coords[0], mol_coords[1]] = 1
Same here (and also this fails upon parsing a list of 2D coordinate arrays)

```suggestion
        mask[mol_coords[:, 0], mol_coords[:, 1]] = np.arange(len(coordinates))
```

2024-08-30 10:39 UTC, closed without merging