General Cleanup and Following the Better Tracing Merger
AFM-SPM/TopoStats pull request #976
Opened 2024-10-21 12:13 UTC by MaxGamill-Sheffield

This PR:
1. Should prevent the logging warning about unclosed files popping up - this was due to the same logger trying to be setup multiple times.

2. Re-enable the stats plotting with the for contour length and average_end_to_end distance as these changed.

3. Actually removes skeletons < min_skel_size from being processed instead of just telling you and doing nothing about it, this prevents a `Skan` error being thrown.

4. Close #929 by switching the logging level mostly to `debug`. Now there is only the following output:
- config + loading:
```
(topo_test) Max:TopoStats Maxgamill$ topostats process -c minicircle_test/mc_config.yaml 
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] The YAML configuration file is valid.
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] The YAML plotting configuration file is valid.
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] Configuration run options are consistent, processing can proceed.
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] Configuration file loaded from      : minicircle_test/mc_config.yaml
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] Scanning for images in              : tests/resources
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] Output directory                    : minicircle_test
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] Looking for images with extension   : .spm
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] Images with extension .spm in tests/resources : 1
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] Thresholding method (Filtering)     : std_dev
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] Thresholding method (Grains)        : std_dev
[Sat, 19 Oct 2024 13:02:52] [INFO    ] [topostats] Extracting image from tests/resources/minicircle.spm
```
- The running of the pipeline:
```
Processing images from tests/resources, results are under minicircle_test:   0%|                                                                               | 0/1 [00:00<?, ?it/s][Sat, 19 Oct 2024 13:02:56] [INFO    ] [topostats] Processing : minicircle
[Sat, 19 Oct 2024 13:02:56] [INFO    ] [topostats] [minicircle] : *** Filtering ***
[Sat, 19 Oct 2024 13:02:58] [INFO    ] [topostats] [minicircle] : Plotting Filtering Images
[Sat, 19 Oct 2024 13:02:59] [INFO    ] [topostats] [minicircle] : Filters stage completed successfully.
[Sat, 19 Oct 2024 13:02:59] [INFO    ] [topostats] [minicircle] : *** Grain Finding ***
[Sat, 19 Oct 2024 13:02:59] [INFO    ] [topostats] [minicircle] : Grains found for direction above : 21
[Sat, 19 Oct 2024 13:02:59] [INFO    ] [topostats] [minicircle] : Plotting Grain Finding Images
[Sat, 19 Oct 2024 13:02:59] [INFO    ] [topostats] [minicircle] : Grain Finding stage completed successfully.
[Sat, 19 Oct 2024 13:02:59] [INFO    ] [topostats] [minicircle] : *** Grain Statistics ***
[Sat, 19 Oct 2024 13:03:00] [INFO    ] [topostats] [minicircle] : Calculated grainstats for 21 grains.
[Sat, 19 Oct 2024 13:03:00] [INFO    ] [topostats] [minicircle] : Grainstats stage completed successfully.
[Sat, 19 Oct 2024 13:03:00] [INFO    ] [topostats] [minicircle] : *** Disordered Tracing ***
[Sat, 19 Oct 2024 13:03:00] [INFO    ] [topostats] [minicircle] : Calculating Disordered Tracing statistics for 21 grains...
[Sat, 19 Oct 2024 13:03:07] [INFO    ] [topostats] [minicircle] : Disordered Tracing stage completed successfully.
[Sat, 19 Oct 2024 13:03:07] [INFO    ] [topostats] [minicircle] : *** Nodestats ***
[Sat, 19 Oct 2024 13:03:07] [INFO    ] [topostats] [minicircle] : Calculating NodeStats statistics for 21 grains...
[Sat, 19 Oct 2024 13:03:07] [INFO    ] [topostats] [minicircle] : NodeStats stage completed successfully.
[Sat, 19 Oct 2024 13:03:07] [INFO    ] [topostats] [minicircle] : *** Ordered Tracing ***
[Sat, 19 Oct 2024 13:03:07] [INFO    ] [topostats] [minicircle] : Calculating Ordered Traces and statistics for 21 grains...
[Sat, 19 Oct 2024 13:03:09] [INFO    ] [topostats] [minicircle] : Ordered Tracing stage completed successfully.
[Sat, 19 Oct 2024 13:03:09] [INFO    ] [topostats] [minicircle] : *** Splining ***
[Sat, 19 Oct 2024 13:03:09] [INFO    ] [topostats] [minicircle] : Calculating Splining statistics for 25 molecules...
[Sat, 19 Oct 2024 13:03:10] [INFO    ] [topostats] [minicircle] : Splining stage completed successfully.
[Sat, 19 Oct 2024 13:03:10] [INFO    ] [topostats] [minicircle] : *** Image Statistics ***
[Sat, 19 Oct 2024 13:03:10] [INFO    ] [topostats] [minicircle] : Saving image to .topostats file
Processing images from tests/resources, results are under minicircle_test: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:17<00:00, 17.50s/it][Sat, 19 Oct 2024 13:03:10] [INFO    ] [topostats] [minicircle] Processing completed.
```
- and the output message:
```
[Sat, 19 Oct 2024 13:03:10] [INFO    ] [topostats] Saving image stats to : minicircle_test/image_stats.csv.
[Sat, 19 Oct 2024 13:03:10] [INFO    ] [topostats] Saving all height profiles to minicircle_test/height_profiles.json
[Sat, 19 Oct 2024 13:03:10] [INFO    ] [topostats] The YAML summarisation config is valid.
[Sat, 19 Oct 2024 13:03:10] [INFO    ] [topostats] [plotting] Default variable to labels mapping loaded.
[Sat, 19 Oct 2024 13:03:10] [INFO    ] [topostats] Summary plots and statistics will be saved to : minicircle_test/summary_distributions
[Sat, 19 Oct 2024 13:03:12] [INFO    ] [topostats] Folder-wise statistics saved to: minicircle_test/folder_grain_stats.csv
[Sat, 19 Oct 2024 13:03:12] [INFO    ] [topostats] Folder-wise statistics saved to: minicircle_test/folder_disordered_trace_stats.csv
[Sat, 19 Oct 2024 13:03:12] [INFO    ] [topostats] Folder-wise statistics saved to: minicircle_test/folder_mol_stats.csv
[Sat, 19 Oct 2024 13:03:12] [INFO    ] [topostats] 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ COMPLETE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  TopoStats Version           : 2.2.2.dev904+g68868e280.d20241018
  Base Directory              : tests/resources
  File Extension              : .spm
  Files Found                 : 1
  Successfully Processed^1    : 1 (100.0%)
  All statistics              : minicircle_test/all_statistics.csv
  Distribution Plots          : minicircle_test/summary_distributions

  Configuration               : minicircle_test/config.yaml

  Email                       : topostats@sheffield.ac.uk
  Documentation               : https://afm-spm.github.io/topostats/
  Source Code                 : https://github.com/AFM-SPM/TopoStats/
  Bug Reports/Feature Request : https://github.com/AFM-SPM/TopoStats/issues/new/choose
  Citation File Format        : https://github.com/AFM-SPM/TopoStats/blob/main/CITATION.cff

  ^1 Successful processing of an image is detection of grains and calculation of at least
     grain statistics. If these have been disabled the percentage will be 0.

  If you encounter bugs/issues or have feature requests please report them at the above URL
  or email us.

  If you have found TopoStats useful please consider citing it. A Citation File Format is
  linked above and available from the Source Code page.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2024-10-21 13:23 UTC, ns-rse commented
Neat, what does `minicircle_test/mc_config.yaml` look like now? I've tried this and still get verbose `INFO`, tried switching `log_level: warning` in a custom output but had very little output beyond the `tqdm` process bar.

2024-10-22 10:09 UTC, ns-rse requested changes
With the `topostats/default_config.yaml` I still get a lot of `LOGGER.info()` output...

```
❱ topostats process -c test_logging_config.yaml
2024-10-22 10:47:45.456635: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-22 10:47:45.459708: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-22 10:47:45.467540: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-22 10:47:45.482635: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-22 10:47:45.486386: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-22 10:47:45.497009: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-22 10:47:46.318670: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] The YAML configuration file is valid.
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] The YAML plotting configuration file is valid.
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Configuration run options are consistent, processing can proceed.
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 100 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[mask_cmap] : blue_purple_green > blue_purple_green 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 200 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 200 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 600 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Updated config config[savefig_dpi] : 300 > 100 
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Configuration file loaded from      : test_logging_config.yaml
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Scanning for images in              : /home/neil/work/git/hub/AFM-SPM/TopoStats
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Output directory                    : output
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Looking for images with extension   : .spm
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Images with extension .spm in /home/neil/work/git/hub/AFM-SPM/TopoStats : 1
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Thresholding method (Filtering)     : std_dev
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Thresholding method (Grains)        : std_dev
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Extracting image from /home/neil/work/git/hub/AFM-SPM/TopoStats/tests/resources/minicircle.spm
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] Loading image from : /home/neil/work/git/hub/AFM-SPM/TopoStats/tests/resources/minicircle.spm
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] [minicircle] : Loaded image from : /home/neil/work/git/hub/AFM-SPM/TopoStats/tests/resources/minicircle.spm
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] [minicircle] : Extracted channel Height
[Tue, 22 Oct 2024 10:47:47] [INFO    ] [topostats] [minicircle] : Pixel to nm scaling : 0.4940029296875
Exception [...]

2024-10-22 14:19 UTC, MaxGamill-Sheffield commented on topostats/processing.py
>      grainstats_df : pd.DataFrame, optional
done

2024-10-22 14:20 UTC, MaxGamill-Sheffield commented on topostats/processing.py
> +        The grain statistics dataframe to be added to. by default an empty grainstats dataframe.
Aye yes that sounds better. I didn't which side of the fence to be if None could be taken but was converted to something else immediately - your comment makes a lot of sense.

2024-10-22 14:40 UTC, MaxGamill-Sheffield commented
> With the `topostats/default_config.yaml` I still get a lot of `LOGGER.info()` output...

This is very unusual as I only see the following when running a single file:
```
(topo_test) Max:TopoStats Maxgamill$ topostats process -c workshop/ws_config.yaml
[Tue, 22 Oct 2024 15:24:40] [INFO    ] [topostats] The YAML configuration file is valid.
[Tue, 22 Oct 2024 15:24:41] [INFO    ] [topostats] The YAML plotting configuration file is valid.
[Tue, 22 Oct 2024 15:24:41] [INFO    ] [topostats] Configuration run options are consistent, processing can proceed.
[Tue, 22 Oct 2024 15:24:41] [INFO    ] [topostats] Configuration file loaded from      : workshop/ws_config.yaml
[Tue, 22 Oct 2024 15:24:41] [INFO    ] [topostats] Scanning for images in              : workshop
[Tue, 22 Oct 2024 15:24:41] [INFO    ] [topostats] Output directory                    : workshop
[Tue, 22 Oct 2024 15:24:41] [INFO    ] [topostats] Looking for images with extension   : .spm
[Tue, 22 Oct 2024 15:24:41] [INFO    ] [topostats] Images with extension .spm in workshop : 1
[Tue, 22 Oct 2024 15:24:41] [INFO    ] [topostats] Thresholding method (Filtering)     : std_dev
[Tue, 22 Oct 2024 15:24:41] [INFO    ] [topostats] Thresholding method (Grains)        : std_dev
[Tue, 22 Oct 2024 15:24:41] [INFO    ] [topostats] Extracting image from workshop/20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022.spm
Processing images from workshop, results are under workshop:   0%|                                                                                             | 0/1 [00:00<?, ?it/s][Tue, 22 Oct 2024 15:24:44] [INFO    ] [topostats] Processing : 20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022
[Tue, 22 Oct 2024 15:24:44] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : *** Filtering ***
[Tue, 22 Oct 2024 15:24:44] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Plotting Filtering Images
[Tue, 22 Oct 2024 15:24:45] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Filters stage completed successfully.
[Tue, 22 Oct 2024 15:24:45] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : *** Grain Finding ***
[Tue, 22 Oct 2024 15:24:45] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Grains found for direction above : 2
[Tue, 22 Oct 2024 15:24:45] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Plotting Grain Finding Images
[Tue, 22 Oct 2024 15:24:46] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Grain Finding stage completed successfully.
[Tue, 22 Oct 2024 15:24:46] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : *** Grain Statistics ***
[Tue, 22 Oct 2024 15:24:46] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Calculated grainstats for 2 grains.
[Tue, 22 Oct 2024 15:24:46] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Grainstats stage completed successfully.
[Tue, 22 Oct 2024 15:24:46] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : *** Disordered Tracing ***
[Tue, 22 Oct 2024 15:24:46] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Calculating Disordered Tracing statistics for 2 grains...
[Tue, 22 Oct 2024 15:24:48] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Disordered Tracing stage completed successfully.
[Tue, 22 Oct 2024 15:24:48] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : *** Nodestats ***
[Tue, 22 Oct 2024 15:24:48] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Calculating NodeStats statistics for 2 grains...
[Tue, 22 Oct 2024 15:24:48] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : NodeStats stage completed successfully.
[Tue, 22 Oct 2024 15:24:48] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : *** Ordered Tracing ***
[Tue, 22 Oct 2024 15:24:48] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Calculating Ordered Traces and statistics for 2 grains...
[Tue, 22 Oct 2024 15:24:48] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Ordered Tracing stage completed successfully.
[Tue, 22 Oct 2024 15:24:48] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : *** Splining ***
[Tue, 22 Oct 2024 15:24:48] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Calculating Splining statistics for 2 molecules...
[Tue, 22 Oct 2024 15:24:49] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Splining stage completed successfully.
[Tue, 22 Oct 2024 15:24:49] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : *** Image Statistics ***
[Tue, 22 Oct 2024 15:24:49] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] : Saving image to .topostats file
Processing images from workshop, results are under workshop: 100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.04s/it][Tue, 22 Oct 2024 15:24:49] [INFO    ] [topostats] [20230823_TAF_IR_minicircle_1.5ng_CaptureFile.0_00022] Processing completed.
Processing images from workshop, results are under workshop: 100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.04s/it]
[Tue, 22 Oct 2024 15:24:49] [INFO    ] [topostats] Saving image stats to : workshop/image_stats.csv.
[Tue, 22 Oct 2024 15:24:49] [INFO    ] [topostats] Saving all height profiles to workshop/height_profiles.json
[Tue, 22 Oct 2024 15:24:49] [INFO    ] [topostats] The YAML summarisation config is valid.
[Tue, 22 Oct 2024 15:24:49] [INFO    ] [topostats] [plotting] Default variable to labels mapping loaded.
[Tue, 22 Oct 2024 15:24:49] [INFO    ] [topostats] Summary plots and statistics will be saved to : workshop/summary_distributions
[Tue, 22 Oct 2024 15:24:50] [INFO    ] [topostats] Folder-wise statistics saved to: workshop/folder_grain_stats.csv
[Tue, 22 Oct 2024 15:24:50] [INFO    ] [topostats] Folder-wise statistics saved to: workshop/folder_disordered_trace_stats.csv
[Tue, 22 Oct 2024 15:24:51] [INFO    ] [topostats] Folder-wise statistics saved to: workshop/folder_mol_stats.csv
[Tue, 22 Oct 2024 15:24:51] [INFO    ] [topostats] 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ COMPLETE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  TopoStats Version           : 2.2.2.dev923+gd3444cdc8
  Base Directory              : workshop
  File Extension              : .spm
  Files Found                 : 1
  Successfully Processed^1    : 1 (100.0%)
  All statistics              : workshop/all_statistics.csv
  Distribution Plots          : workshop/summary_distributions

  Configuration               : workshop/config.yaml

  Email                       : topostats@sheffield.ac.uk
  Documentation               : https://afm-spm.github.io/topostats/
  Source Code                 : https://github.com/AFM-SPM/TopoStats/
  Bug Reports/Feature Request : https://github.com/AFM-SPM/TopoStats/issues/new/choose
  Citation File Format        : https://github.com/AFM-SPM/TopoStats/blob/main/CITATION.cff

  ^1 Successful processing of an image is detection of grains and calculation of at least
     grain statistics. If these have been disabled the percentage will be 0.

  If you encounter bugs/issues or have feature requests please report them at the above URL
  or email us.

  If you have found TopoStats useful please consider citing it. A Citation File Format is
  linked above and available from the Source Code page.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


(topo_test) Max:TopoStats Maxgamill$ 
```

> Do we w [...]

2024-10-22 14:42 UTC, MaxGamill-Sheffield commented on topostats/tracing/ordered_tracing.py
I realised that and so tried to keep it all commit specific as Sylvia told me you go through PR's commit-by-commit and that this is best practice

2024-10-22 14:44 UTC, MaxGamill-Sheffield commented on topostats/tracing/disordered_tracing.py
>                  + f"{cropped_image_index} failed. Consider raising an issue on GitHub. Error: ",
cool, didn't know this so will add it to my knowlege bank :)

2024-10-23 12:24 UTC, ns-rse commented
> No idea what this is and haven't seen it before. I looks like it might be from a Tensorflow dependancy? I could take a look into it but I don't think its from anything that has been added in this PR or the better tracing ones - this might be from the unets?

Yes, this is due to Tensorflow.

> We could disable all warnings with the following but is this wise?
>

But then users wouldn't see TopoStats warnings so I'm not sure that is what is required.

A quick [search](https://duckduckgo.com/?q=silence+tensorflow+warnings) led me to [this solution](https://bobbyhadz.com/blog/disable-suppress-tensorflow-warnings)

Putting the following in `__init__.py` would suppress the warnings

```python
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
```

Incoming PR (with small "bonus").

> Are you able to retry this branch and double check the output for you is not the same as I see?

Seems I hadn't `git pull`'d the branch, my apologies. Much quieter output now, once the TensorFlow message supression is merged this is good to go.


## `loguru`

I wasn't proposing overhauling things with regards to `loguru` here and have made some simple forays into switching on Monday but its a bit more involved so I've shelved it in favour of focusing on #517 as a priority.

I understand the need to always do things "quickly" but sometimes its a false economy spending time on a quick fix and then (maybe) going back and doing the larger piece of work that should have been done in the first place (this is in essence what accumulates as "technical debt"). We don't always get things right first time, and I know I'm continually learning better ways of doing things. Taking ownership of work and doing it to the best of our ability helps minimise the accumulation of technical debt.

2024-10-23 13:04 UTC, MaxGamill-Sheffield commented
> Putting the following in `__init__.py` would suppress the warnings
> 
> ```python
> import os
> 
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
> ```

Cool I've added this now! @llwiggins have you tested this yet and is it good to go?

2024-10-24 06:12 UTC, merged

2024-10-24 09:49 UTC, ns-rse commented
There is now duplicate lines for disabling Tensor Flow.

I will remove one.